[tool.poetry]
name = "csse6400-p1"
version = "0.1.0"
description = ""
authors = ["rina <k@rina.fyi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
